version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: damir
      POSTGRES_PASSWORD: damir
      POSTGRES_DB: service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5431
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: